persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 1 
  datastores:
    default:
      sql:
        pluginName: "postgres12"
        databaseName: "orderdb"
        connectAddr: "postgres:5432"
        connectProtocol: "tcp"
        user: "orderuser"
        password: "orderpass"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
    visibility:
      sql:
        pluginName: "postgres12"
        databaseName: "orderdb"
        connectAddr: "postgres:5432"
        connectProtocol: "tcp"
        user: "orderuser"
        password: "orderpass"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"


global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "0.0.0.0"

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnIP: "0.0.0.0"

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnIP: "0.0.0.0"

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnIP: "0.0.0.0"

  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnIP: "0.0.0.0"

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "127.0.0.1:7233"

dcRedirectionPolicy:
  policy: "noop"

archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "enabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "enabled"
      URI: "file:///tmp/temporal_archival/development"


workflow:
  workflowExecutionRetentionTTL: "7d"